name: Build AMI with Packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v1.1.2

#    - name: Install dependencies
#      run: |
 #       sudo apt-get update
 #       sudo apt-get install -y jq

    - name: Build AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        packer init .
        packer validate aws-ami-v1.pkr.hcl
        packer build aws-ami-v1.pkr.hcl
